bunq_token: "secret"
ynab_token: "secret"
accounts:
  - bunq_account_name: "Your bunq account name"
    ynab_budget_name: "Your YNAB budget name"
    ynab_account_name: "Your YNAB account name"
    from: "2024-01-13" # optional start date
  - bunq_account_name: "Your bunq account name 2"
    ynab_budget_name: "Your YNAB budget name 2"
    ynab_account_name: "Your YNAB account name 2"
